apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    app: sql
spec:
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2017-latest
        name: sql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        ports:
        - containerPort: 1433
          name: sql
        volumeMounts:
        - name: sql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-persistent-storage
        persistentVolumeClaim:
          claimName: sql-volume-claim